version: "3.8"
services:
  server1: &server
    build: .
    environment:
      - ISUCON_DB=${ISUCON_DB}
      - ISUCON_DB_HOST=${ISUCON_DB_HOST}
      - ISUCON_DB_USER=${ISUCON_DB_USER}
      - ISUCON_DB_PASSWORD=${ISUCON_DB_PASSWORD}
      - ISUCON_DB_PORT=${ISUCON_DB_PORT}
      - REMOTE_DEBUG_PORT=${REMOTE_DEBUG_PORT}
    ports:
      - 11111:80
      - 8080:8080
      - ${REMOTE_DEBUG_PORT}:${REMOTE_DEBUG_PORT}
    tty: true
    volumes:
      - .:/home/ubuntu/webapp
      - ./docker/app/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/app/nginx/server1/sites-available:/etc/nginx/sites-available
      - ./docker/app/nginx/server1/log:/var/log/nginx
    command: /entrypoint.sh
  server2: 
    <<: *server
    ports:
      - 22222:80
      - 8081:8080
    volumes:
      - .:/home/ubuntu/webapp
      - ./docker/app/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/app/nginx/server2/sites-available:/etc/nginx/sites-available
      - ./docker/app/nginx/server2/log:/var/log/nginx
  db:
    platform: linux/x86_64
    build: ./docker/db
    environment:
      - MYSQL_DATABASE=${ISUCON_DB}
      - MYSQL_USER=${ISUCON_DB_USER}
      - MYSQL_PASSWORD=${ISUCON_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./docker/db/initdb:/docker-entrypoint-initdb.d
      - ./docker/db/conf.d:/etc/mysql/conf.d
      - ./docker/db/log:/var/log/mysql